import type { Metadata, Viewport } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "CatalystWells Explore – AI Education & Well-being Platform",
  description:
    "Discover CatalystWells, India's leading AI-powered education platform for attendance, analytics, student well-being, and connected learning ecosystems. Explore the platform before you sign in at catalystwells.in.",
  metadataBase: new URL("https://explore.catalystwells.in"),
  alternates: {
    canonical: "https://explore.catalystwells.in",
  },
  keywords: [
    "AI education platform",
    "school management software",
    "student well-being",
    "education analytics",
    "school ERP India",
    "AI school platform",
    "education technology",
    "student mental health",
  ],
  authors: [{ name: "Catalyst Wells" }],
  openGraph: {
    title: "CatalystWells Explore | Transforming School Education with AI",
    description:
      "Join 500+ schools exploring CatalystWells to enhance academic performance and student well-being.",
    url: "https://explore.catalystwells.in",
    siteName: "CatalystWells Explore",
    images: [
      {
        url: "https://explore.catalystwells.in/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Catalyst Wells - AI-Powered Education Platform",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@CatalystWells",
    title: "CatalystWells Explore – Smart Education with AI",
    description:
      "Explore the AI-powered school platform improving education and mental well-being before you sign in at catalystwells.in.",
    images: ["https://explore.catalystwells.in/og-image.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Icons are auto-generated by icon.tsx and apple-icon.tsx
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#0A84FF",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "CatalystWells Explore",
    "url": "https://explore.catalystwells.in",
    "logo": "https://explore.catalystwells.in/logo.png",
    "founder": "Rowanberg",
    "sameAs": [
      "https://x.com/CatalystWells",
      "https://www.linkedin.com/company/catalystwells",
      "https://www.facebook.com/catalystwells",
      "https://www.instagram.com/catalystwells",
      "https://www.youtube.com/@catalystwells"
    ],
    "description": "AI-driven education management platform empowering schools to improve academic performance, communication, and student well-being.",
    "foundingDate": "2024",
    "contactPoint": {
      "@type": "ContactPoint",
      "email": "legal@catalystwells.in",
      "telephone": "+91-7010319269",
      "contactType": "customer support",
      "availableLanguage": ["English", "Hindi"],
      "areaServed": "IN"
    },
  };

  const localBusinessSchema = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": "https://explore.catalystwells.in",
    "name": "CatalystWells Explore",
    "image": "https://explore.catalystwells.in/logo.png",
    "url": "https://explore.catalystwells.in",
    "telephone": "+91-7010319269",
    "email": "legal@catalystwells.in",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "123 Education Hub, Tech Park",
      "addressLocality": "Bangalore",
      "addressRegion": "Karnataka",
      "postalCode": "560001",
      "addressCountry": "IN"
    },
    "geo": {
      "@type": "GeoCoordinates",
      "latitude": 12.9716,
      "longitude": 77.5946
    },
    "openingHoursSpecification": {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
      ],
      "opens": "09:00",
      "closes": "18:00"
    },
    "sameAs": [
      "https://x.com/CatalystWells",
      "https://www.linkedin.com/company/catalystwells",
      "https://www.facebook.com/catalystwells",
      "https://www.instagram.com/catalystwells",
      "https://www.youtube.com/@catalystwells"
    ],
    "priceRange": "₹₹"
  };

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=Space+Grotesk:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </head>
      <body>
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-7WF3H6K871"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-7WF3H6K871');
            `,
          }}
        />

        {/* Structured Data */}
        <Script
          id="organization-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <Script
          id="local-business-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
        />
        {children}
      </body>
    </html>
  );
}
