import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Catalyst Wells – AI Education & Well-being Platform",
  description: "Empowering schools with AI analytics, student well-being tracking, and connected learning ecosystems.",
  metadataBase: new URL("https://www.catalystwells.com"),
  alternates: {
    canonical: "https://www.catalystwells.com",
  },
  keywords: [
    "AI education platform",
    "school management software",
    "student well-being",
    "education analytics",
    "school ERP India",
    "AI school platform",
    "education technology",
    "student mental health",
  ],
  authors: [{ name: "Catalyst Wells" }],
  openGraph: {
    title: "Catalyst Wells | Transforming School Education with AI",
    description: "Join 500+ schools using Catalyst Wells to enhance academic performance and student well-being.",
    url: "https://www.catalystwells.com",
    siteName: "Catalyst Wells",
    images: [
      {
        url: "https://www.catalystwells.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Catalyst Wells - AI-Powered Education Platform",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@CatalystWells",
    title: "Catalyst Wells – Smart Education with AI",
    description: "AI-powered school platform improving education and mental well-being.",
    images: ["https://www.catalystwells.com/og-image.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Icons are auto-generated by icon.tsx and apple-icon.tsx
  manifest: "/manifest.json",
  themeColor: "#0A84FF",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "Catalyst Wells",
    "url": "https://www.catalystwells.com",
    "logo": "https://www.catalystwells.com/logo.png",
    "founder": "Rowanberg",
    "sameAs": [
      "https://x.com/CatalystWells",
      "https://www.linkedin.com/company/catalystwells",
    ],
    "description": "AI-driven education management platform empowering schools to improve academic performance, communication, and student well-being.",
    "foundingDate": "2024",
    "contactPoint": {
      "@type": "ContactPoint",
      "email": "support@catalystwells.com",
      "contactType": "customer support",
      "availableLanguage": ["English", "Hindi"],
    },
  };

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=Space+Grotesk:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </head>
      <body>
        <Script
          id="structured-data"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        {children}
      </body>
    </html>
  );
}
